[project]
name = "yc-analyzed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "instructor[litellm]==1.6.3",
    "litellm==1.48.0",
    "pydantic==2.9.2",
    "python-dotenv==1.0.1",
    "selenium==4.25.0",
]
